### ISSUE TITLE
Warning/Error messages for SSASimulator

### ISSUE THREAD

**Issue by ayush9pandey** [ananswam/bioscrape#12]
When running stochastic simulations, it would be good to have bioscrape print out warning or error messages when things get ill conditioned (something blows up, something goes negative etc.) and stop the simulation instead of freezing the kernel. I understand that `SafeModeSSASimulator` was a step in this direction but still I have been facing the problem of dead kernel a lot (most likely because it is easy for the stochastic simulator to blow up some calculation)

**Comment by ayush9pandey** [comment]
The broader context of this issue would be to have better data type validation and user error/warning messages all over bioscrape, rather than Python giving the user somewhat cryptic error messages when things break.

**Comment by WilliamIX** [comment]
What would a wish-list of warnings / error cases look like? I have mostly used bioscrape for ODE simulations which is very stable. There is an error-checking speed trade off - but I bet many errors/warnings could be issued before simulations even begin.

**Comment by ananswam** [comment]
Yes, exactly. The reason that I removed a ton of error checking "live" was
it was killing speed, but I do agree that it's incredibly annoying when it
just goes negative and segfaults as well without saying anything. I'm not
sure what the best way to get around this is, other than SafeMode. Any
ideas?

**Comment by WilliamIX** [comment]
I think checking if a propensity is negative is worth doing and is inexpensive (we are already running through all the propensities anyways, so this is a very small slow down). Species counts are harder but if the counts become higher than some very large number (say 100,000 or 1000000 of a single species) it might be worth giving a warning (also a cheap check).

**Comment by WilliamIX** [comment]
This was fixed via the SafeCSimModelInterface which can be accessed quickly via py_simulate_model(...safe = True)
