### ISSUE TITLE
Creating Safe Propensities

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#17]
The issue: if the functional form of a propensity does not depend on the reactants it consumes, a reaction can fire resulting in negative counts and/or concentrations. Can we add - to all propensity types - some (optional?) way to make sure the reaction doesn't fire in this case. There will be a cost of speed, so what is the best way to implement this?

Ideas:

1. Safe propensities as a new type of propensity. Option to create all propensities as "safe". Safe propensities automatically check for these kinds of errors. A model could have a mixture of safe and unsafe propensities.
2. Safe Interfaces as a new kind (or option) in the SimInterface object. These interfaces will automatically do all of this checking, regardless of propensity type.

Complications: the propensity check is different between the stochastic and the deterministic case. In the stochastic case, #Reactants Consumed must be >= #Reactants available for the propensity to fire. In the Deterministic case #Reactants Available must be > 0 for the propensity to fire (but this still allows the concentrations to go negative due to integration errors). How do we deal with the different kinds of checks depending on which kind of simulator is running? This is related to issue #16 . Currently, the sim interface and model is agnostic to the kind of simulation - however this might not be ideal in some cases.

**Comment by ayush9pandey** [comment]
In line with our discussion on safe propensities, I observed that every time when a rate of a reaction has something in the denominator going to zero, causes the stochastic simulator to freeze the kernel.

**Comment by WilliamIX** [comment]
So we could just check numpy.isnan() for the denominator --> infinity case right? For general propensities it will be hard to figure out what a "denominator" is and there might be multiple.

**Comment by WilliamIX** [comment]
This has been fixed with a safemode interface: SafeModelCSimInterface which also checks for species going over a certain count (set via the interface constructor), species going negative, volume going over a certain amount (set via the interface constructor), or volume going negative. Can be accessed easily with default thresholds of 1000 by passing in the keyword safe=True to py_simulate_model.
