### ISSUE TITLE
Link broken in Wiki/Installation - Windows C++ compiler.

### ISSUE THREAD

**Issue by ayush9pandey** [ananswam/bioscrape#23]
The Windows C++ compiler link given on Wiki/Installation https://landinghub.visualstudio.com/visual-cpp-build-tools does not work anymore because of some changes on the visual studio webpage. 

I don't have access to the repository to make the change on the Wiki myself.

**Comment by ayush9pandey** [comment]
I believe the correct link is the following 
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

**Comment by ayush9pandey** [comment]
Also adding here that with Windows it has always been painful for me to get the C++ compiler working. An option is to blindly download and install the heavy Visual Studio "Workloads" (packaged tools provided by Microsoft). Another option is to pick and choose to install only the ones you need. I took the second option and in my case, I ended up installing the following from the Visual Studio Installation Manager to get bioscrape installation working - 
  
1. Visual C++ Build Tools Core Features 
2. VC++ 2017 (or later versions should work too)
3. Visual C++ tools for CMake
4. Visual Studio C++ core features 
5. C++ support
6. .NET framework (3.5 for development tools and 4.6)

Some of the above might not be mandatory though, I haven't checked that.

**Comment by WilliamIX** [comment]
If you install anaconda, instead of say miniconda, I think things are easier. That said, how should we document this on the wiki?

**Comment by ayush9pandey** [comment]
Yeah.

I gave up on making everything work on my other laptop so I don't have concrete installation steps ready. 

For the wiki, we could probably just say that Anaconda/Miniconda is required rather than the how it is currently saying that it is optional. Also, getting the right C++ compiler for windows is an important issue. The current link given on the wiki is broken, so we need to put a correct link over there.

**Comment by ananswam** [comment]
Fixed this using Ayush's suggestions
