### ISSUE TITLE
Installation instructions missing package dependencies

### ISSUE THREAD

**Issue by murrayrm** [ananswam/bioscrape#27]
In order to run the examples as described in the [installation instructions](https://github.com/ananswam/bioscrape/wiki/Installation), you need to install `jupyter`, `matplotlib`, and `sympy`.  Installation of these files should be added to the installation instructions.

**Comment by WilliamIX** [comment]
On linux emcee is also needed and not included with anaconda in order to run the example notebook.

**Comment by WilliamIX** [comment]
libsbml also not included in dependencies and not included in linux anaconda (or other anaconda distributions most likely).

**Comment by murrayrm** [comment]
In preparing for BE 240, I came across this error again.

**Comment by murrayrm** [comment]
Here is the complete set of additional things I had to install to get this working:
```
conda install jupyter matplotlib sympy pandas
```

**Comment by WilliamIX** [comment]
Added all of these to the list - usually these 4 are included with anaconda

**Comment by murrayrm** [comment]
For posterity: I did a full anaconda install and definitely didn't get sympy or pandas.

**Comment by ayush9pandey** [comment]
Yes, I also remember having to install sympy and pandas separately.
