### ISSUE TITLE
lineage installation issues on linux (redhat @ caltech)

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#30]
Here is the error message - it occurs at the very start of the cython file. It has nothing to do with the .pyd document (which can/should be removed because it is not used in lineage). No idea what the problem is.

[wpoole@synthetic bioscrape]$ python setup.py install lineages
Installing lineages
Warning: Extension name 'bioscrape.lineage' does not match fully qualified name 'lineage' of 'lineage/lineage.pyx'
Compiling lineage/lineage.pyx because it changed.
[1/1] Cythonizing lineage/lineage.pyx

Error compiling Cython file:
------------------------------------------------------------
...

import warnings

cdef class Event():
                ^
------------------------------------------------------------

lineage/lineage.pyx:26:17: Expected an identifier
Traceback (most recent call last):
  File "setup_lineages.py", line 36, in <module>
    ext_modules = cythonize(extensions),
  File "/home/wpoole/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
    cythonize_one(*args)
  File "/home/wpoole/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1161, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: lineage/lineage.pyx

**Comment by ananswam** [comment]
EDIT: Sorry, I was reading the wrong line. That error is because you declared a class with empty parentheses, which is not supported in old versions of Cython. Ideally, if you declare a class that doesn't inherit from anything, just use cdef class Event: rather than Event():.

However, updating Cython will get rid of the issue as well.

**Comment by WilliamIX** [comment]
Awesome, I just figured this out on my own too. I will get rid of the empty parentheses in the code and re-commit, test on windows, and recommit.

**Comment by WilliamIX** [comment]
All examples also run fine on linux!
