### ISSUE TITLE
Parameter ID Function Calls

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#33]
What are the function calls for parameter ID?

Pseudocode below:

ParameterIDFunc [Wrapper around Stan/Emcee]:
Mandatory Inputs:
- Bioscrape Model M
- Parameter Names (List of Strings)
- Cost Function (string identifier or custom function)
- Data
- Deterministic / Stochastic (defaults?)

Strongly Suggested Inputs:
- Parameter Priors (dict: str name --> prior parameters)
--Send Warning!

Optional:
- PID Function parameters (eg steps, #walkers, etc)

**Comment by ayush9pandey** [comment]
Closing this issue now, as it was addressed with #35
