### ISSUE TITLE
Priors

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#34]
Here is the class definition - will be subclassed for univariate, bivariate, etc.

cdef class Prior(Likelihood):
    cdef Model m
    cdef CsimInterface csim
    cdef list parameters
    cdef Distribution dist
    
    cdef double get_log_likelihood(self)

What distributions do we need? Currently only have uniform.

**Comment by WilliamIX** [comment]
Distributions: (univariate and multivariate versions) uniform, Guassian, custom.

**Comment by ayush9pandey** [comment]
The PR #35 only deals with the most simple but most common use case of having Gaussian or Uniform priors for different parameters. It allows you to mix and match the distributions for each parameter. 

In the long run, we would want to have an advanced version of the Priors class that could handle multivariate distributions, and some other computational options with Priors distributions.

**Comment by WilliamIX** [comment]
Moved to https://github.com/biocircuits/bioscrape/issues/9
