### ISSUE TITLE
Creating rules using Model API fails

### ISSUE THREAD

**Issue by ayush9pandey** [ananswam/bioscrape#40]
MWE that fails to run - 

```
allrules = [('assignment', {'equation': 'k1'}), ('assignment', {'equation': 'k1'})]
allparams = [('k1',10)]
m = Model(rules = allrules, parameters = allparams)
m.write_bioscrape_xml('models/sbml_test_bioscrape.xml')
```
On running this, the code just exits and no bioscrape model file is written and no error is printed either.

**Comment by WilliamIX** [comment]
Those are not valid assignment rules. Assignment rules should be of the form "param (or species) = equation".

**Comment by ayush9pandey** [comment]
I didn't get that. I have these two rules that work fine when I don't use the API to create the model

```
allrules = [('assignment', {'equation': 'T / (1 + Keq)'}), ('assignment', {'equation': 'Keq * S1'})]
```

What's the correct way to write the above line of code for the Model class? (here T and S1 are species, Keq is parameter)

**Comment by ayush9pandey** [comment]
I think I got it. The correct way is this (using the rule variable for which the rule is written) - 
```
allrules = [('assignment', {'equation': 'S1 = T / (1 + Keq)'}), ('assignment', {'equation': 'S2 = Keq * S1'})]
```

**Comment by WilliamIX** [comment]
yes {'equation': '[species or paramter] = [equation]'} is the correct syntax. Additionally, I believe that parameters need to start with a "_" like "_Keq" to parse as parameters. Otherwise, they will become new species.

There is a working example of assignment rules in the Getting Started jupyter notebook, towards the end somewhere.

**Comment by ayush9pandey** [comment]
Yes, thanks.
