### ISSUE TITLE
Termination condition for simulation

### ISSUE THREAD

**Issue by rlwillia** [ananswam/bioscrape#48]
Hello! I've been finding this simulation tool extremely useful, and think a feature that would enhance this is to be able to have a rule type which will terminate a simulation when a specified condition is met. What I have in mind I think would be a heaviside function that would end the simulation when a species, or the sum of a subset of the species (kept track of by an additive rule) exceeds or goes below some threshold. Ideally it would return the truncated simulation. Thanks for your help!

Best,

Rory

**Comment by WilliamIX** [comment]
Thanks for this suggestion! In the future can you please leave comments on the biocircuits fork of bioscrape which we have officially moved to?
