### ISSUE TITLE
Can you upload the plasmid replication model?

### ISSUE THREAD

**Issue by LittleHannah** [ananswam/bioscrape#49]
There is a plasmid replication model described in the paper, but was not upload in the repository, can you share the code?

**Comment by WilliamIX** [comment]
Just a heads up - we've mostly moved to using a different repository: https://github.com/biocircuits/bioscrape - to get the newest updates from the code, please follow that fork.

In terms of the plasmid replication model, I don't have access to the specific parameters we used but it was something like:

P --> 2P at rate = hillnegative(P) = k / (K + P^n)

Where k, K, and n have to be tuned based upon the division rate of the cells, mean plasmid copy number, and desired variance in the Plasmid copy number.

**Comment by ananswam** [comment]
See attached.
[plasmid_control.xml.zip](https://github.com/ananswam/bioscrape/files/4748052/plasmid_control.xml.zip)
